### ISSUE TITLE
Backbone missing

### ISSUE THREAD

**Issue by tr-s3-2020** [Jee-King/AFNet#2]
Hi, I've encountered this issue when running this project:
Traceback (most recent call last):
  File "run_training.py", line 58, in <module>
    main()
  File "run_training.py", line 53, in main
    run_training(args.train_module, args.train_name, args.cudnn_benchmark)
  File "run_training.py", line 42, in run_training
    expr_func(settings)
  File "/home/ziyangshen/Projects/AFNet/ltr/train_settings/afnet/afnet.py", line 93, in run
    net = dimpnet.klcedimpnet18(filter_size=settings.target_filter_sz, backbone_pretrained=True, optim_iter=5,
  File "/home/ziyangshen/Projects/AFNet/ltr/admin/model_constructor.py", line 14, in f_wrapper
    output = f(*args, **kwds)
  File "/home/ziyangshen/Projects/AFNet/ltr/models/tracking/dimpnet.py", line 275, in klcedimpnet18
    backbone_net = backbones.resnet18(pretrained=backbone_pretrained, frozen_layers=frozen_backbone_layers)
AttributeError: module 'ltr.models.backbone' has no attribute 'resnet18'

It seems that there's a lot of backbones missing under /ltr/models/backbone, including resnet18, resnet50, resnet_baby ,fusion etc.
Also, are there any pretrained models provided for this project? Thanks.

**Comment by skxooo** [comment]
> Hi, I've encountered this issue when running this project: Traceback (most recent call last): File "run_training.py", line 58, in main() File "run_training.py", line 53, in main run_training(args.train_module, args.train_name, args.cudnn_benchmark) File "run_training.py", line 42, in run_training expr_func(settings) File "/home/ziyangshen/Projects/AFNet/ltr/train_settings/afnet/afnet.py", line 93, in run net = dimpnet.klcedimpnet18(filter_size=settings.target_filter_sz, backbone_pretrained=True, optim_iter=5, File "/home/ziyangshen/Projects/AFNet/ltr/admin/model_constructor.py", line 14, in f_wrapper output = f(*args, **kwds) File "/home/ziyangshen/Projects/AFNet/ltr/models/tracking/dimpnet.py", line 275, in klcedimpnet18 backbone_net = backbones.resnet18(pretrained=backbone_pretrained, frozen_layers=frozen_backbone_layers) AttributeError: module 'ltr.models.backbone' has no attribute 'resnet18'
> 
> It seems that there's a lot of backbones missing under /ltr/models/backbone, including resnet18, resnet50, resnet_baby ,fusion etc. Also, are there any pretrained models provided for this project? Thanks.

you may can find the backbone in pytracking package:https://github.com/visionml/pytracking

**Comment by tr-s3-2020** [comment]
Thank you for your kind reply. What about the pretrained models? Thanks.
